// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3t_dEh9NvRUjS8XfBGof1QFHYF-5atJo',
    appId: '1:550373472553:web:e70625559f2ed1d5ac9f38',
    messagingSenderId: '550373472553',
    projectId: 'fixmate-2026',
    authDomain: 'fixmate-2026.firebaseapp.com',
    storageBucket: 'fixmate-2026.firebasestorage.app',
    measurementId: 'G-4C93GT7N71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BVTKgGY9uf3odDj7Mcb1qQBrT9_AapY',
    appId: '1:550373472553:android:786ac6d7831d1126ac9f38',
    messagingSenderId: '550373472553',
    projectId: 'fixmate-2026',
    storageBucket: 'fixmate-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuU1gevK6PUbfJNBclEI9BnmJngwLMM08',
    appId: '1:550373472553:ios:c09de07141105c9fac9f38',
    messagingSenderId: '550373472553',
    projectId: 'fixmate-2026',
    storageBucket: 'fixmate-2026.firebasestorage.app',
    iosBundleId: 'com.fixmate.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuU1gevK6PUbfJNBclEI9BnmJngwLMM08',
    appId: '1:550373472553:ios:c09de07141105c9fac9f38',
    messagingSenderId: '550373472553',
    projectId: 'fixmate-2026',
    storageBucket: 'fixmate-2026.firebasestorage.app',
    iosBundleId: 'com.fixmate.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3t_dEh9NvRUjS8XfBGof1QFHYF-5atJo',
    appId: '1:550373472553:web:753721570eaab6c1ac9f38',
    messagingSenderId: '550373472553',
    projectId: 'fixmate-2026',
    authDomain: 'fixmate-2026.firebaseapp.com',
    storageBucket: 'fixmate-2026.firebasestorage.app',
    measurementId: 'G-BG576JHEQT',
  );
}
